### ISSUE TITLE
Not getting data from API.

### ISSUE THREAD

**Issue by ghost** [anitaa1990/PagingLibrary-Sample#4]
java.net.UnknownHostException: Unable to resolve host "newsapi.org": No address associated with hostname

**Comment by anitaa1990** [comment]
this is usually an internet problem. And since the api is still working in a lot of devices, I am going to assume it was an internet issue in your device. Feel free to reopen if you find any other issues.

**Comment by Ayesha-Adhikari** [comment]
I am not able to resolve this issue. Can you please tell me how you got through this?
